integrate cli changes for listener events and timestamp
pomerium/desktop-client pull request #57
Opened 2021-12-08 18:22 UTC by nhayfield

## Summary
Integrate listener status updates and timestamp from the cli
Requires branch wasaga/listener-events of the cli

## Checklist

- [ ] reference any related issues
- [ ] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [ ] add appropriate tag (`improvement` / `bug` / etc)
- [ ] ready for review

2021-12-08 22:00 UTC, wasaga requested changes

2021-12-08 22:08 UTC, nhayfield commented on src/renderer/pages/ConnectionView.tsx
>          message = msg.peerAddr + ' disconnected from ' + remoteAddr;
this is already handled separately:
`if (msg.lastError) {
      message =
        msg.peerAddr +
        'failed to connect to ' +
        remoteAddr +
        ':' +
        msg.lastError;
    }`

2021-12-08 22:08 UTC, nhayfield commented on src/renderer/pages/ConnectionView.tsx
>          message = msg.peerAddr + ' disconnected from ' + remoteAddr;
this is because you don't have a separate status for errors

2021-12-08 22:09 UTC, nhayfield commented on src/renderer/pages/ConnectionView.tsx
>        default:
lol it will look really silly in the code but ok

2021-12-08 22:27 UTC, wasaga commented on src/renderer/pages/ConnectionView.tsx
>          message = msg.peerAddr + ' disconnected from ' + remoteAddr;
a proper way to do that is using protobuf `oneof` which as we discussed creates an inconvenience on the TS generated code side.. thus the optional error fields.

2021-12-08 22:33 UTC, nhayfield commented on src/renderer/pages/ConnectionView.tsx
>          message = msg.peerAddr + ' disconnected from ' + remoteAddr;
i don't think the errors actually work. I have not seen any so far.

2021-12-09 16:06 UTC, nhayfield commented on src/renderer/pages/ConnectionView.tsx
>        default:
wow looks like enums break it on mac only !

2021-12-09 18:12 UTC, wasaga approved these changes

2021-12-09 20:04 UTC, merged